name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのソースコードをチェックアウト
      - uses: actions/checkout@v4

      # Rustのセットアップ（Toolchainなどを指定可能）
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # WebAssemblyターゲットの追加
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      # Clippyによるリントチェック
      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # フォーマットチェック
      - name: Check code formatting
        run: cargo fmt --all -- --check

      # テスト実行
      - name: Run Tests
        run: cargo test --all --verbose

      # DFXのセットアップ
      - name: Install DFX
        env:
          DFX_VERSION: latest
        run: sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)" < /dev/null

      # DFXのバージョン確認
      - name: Check DFX version
        run: dfx --version

      # ローカルネットワークの起動
      - name: Start DFX network
        run: dfx start --clean --background

      # DFXのデプロイ
      - name: Deploy with DFX
        run: dfx deploy